title: "Header"
description: |
  The header is created with a clean and simple design that matches the style of the website through simplicity and colour. The Header can be combined with button and icons and is to be used on every page throughout the site.
