description: |
  The card section is used where there is a section that inludes multiple pieces, creating a card style. Cards can be combined with icons, buttons as well as sections.

patterns:
  project-card:
    title: "Project Card"
    description: |
      The card will be used as the navigation to the project page. It will be seen on the main home page.
    fields:
      - name: heading
        type: string
        example: "INSERT TEXT"
      - name: image
        type: string
        example: "hues-pic.jpg"
      - name: url
        type: url
        example: "#"
      - name: alt
        type: string
        example: "Presentation"
